# Generated by Django 3.1.1 on 2020-09-29 13:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ServPro', '0002_auto_20200929_1835'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='service1',
            new_name='service',
        ),
    ]
