# Generated by Django 3.1.1 on 2020-09-30 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServPro', '0003_auto_20200929_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='Image',
        ),
    ]
